# Generated by Django 4.2.6 on 2023-11-09 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('author', models.ForeignKey(default='Community', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_date', 'title'],
            },
        ),
    ]
