# Generated by Django 4.2.6 on 2023-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
