# Generated by Django 4.2.5 on 2023-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date', 'title'], 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1234, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
